// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rssjwsknkuzyjhvridxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzc2p3c2tua3V6eWpodnJpZHh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NjE0MDIsImV4cCI6MjA1OTIzNzQwMn0.hxdaPvHq4mfMIC2-nziKRCGeudH-ElI3P-G8n3uOmYM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);